############################################################
# OpenVPN Server - FreeBSD 15.1
############################################################

port 1194
proto udp

dev tun

disable-dco
duplicate-cn

topology subnet

server 10.8.0.0 255.255.255.0

# ----------------------------------------------------------
# Routing
# ----------------------------------------------------------

push "route 172.16.10.0 255.255.255.0"

# ----------------------------------------------------------
# PKI
# ----------------------------------------------------------

ca /usr/local/etc/openvpn/pki/ca.crt
cert /usr/local/etc/openvpn/pki/server.crt
key /usr/local/etc/openvpn/pki/server.key

dh /usr/local/etc/openvpn/pki/dh.pem

# ----------------------------------------------------------
# TLS
# ----------------------------------------------------------

tls-crypt /usr/local/etc/openvpn/pki/easyrsa-tls.key

tls-version-min 1.2

verify-client-cert require
remote-cert-tls client

# ----------------------------------------------------------
# Crypto
# ----------------------------------------------------------

data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-256-GCM

auth SHA256

# ----------------------------------------------------------
# Client handling
# ----------------------------------------------------------

keepalive 10 120

persist-key
persist-tun

user nobody
group nobody

# ----------------------------------------------------------
# Logging
# ----------------------------------------------------------

status /var/log/openvpn-status.log

verb 3
